version: '3'

services:

    db:
        image: postgres
        container_name: postgresDB
        env_file:
            - ./ultra_db/.env
        ports:
            - "5445:5432"
        volumes:
            - "postgres-data:/data/postgres"
        networks:
            - ultra-network

    worker:
        build: ./ultra-task
        ports:
            - 3700:4000
        links:
            - db:db
        depends_on:
            - db
        env_file:
            - ./ultra-task/.env
        networks:
            - ultra-network

volumes:
    postgres-data:

networks:
    ultra-network: